on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup SSH Key
      run: |
        mkdir -p ~/.ssh
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -v ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

    - name: Connect
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} -v
   
    - name: Clean
      run: |
        rm -rf ~/.ssh
